# Generated by Django 4.2.20 on 2025-04-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nyumbaAI_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="houselisting",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="houselisting",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="houselisting",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="houselisting",
            name="price",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="houselisting",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
