# Generated by Django 4.2.20 on 2025-04-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nyumbaAI_app", "0002_alter_houselisting_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="houselisting",
            name="link",
            field=models.URLField(blank=True, default="#", max_length=500, null=True),
        ),
    ]
